### ISSUE TITLE
Compilation errors when generating sources for Microsoft.UI.Xaml.Controls.WebView2

### ISSUE THREAD

**Issue by biscuitehh** [thebrowsercompany/swift-winrt#130]
**Issue**
Using `swift-winrt` to generate bindings for `WebView2` results in Swift code that doesn't compile.

**Environment**
IDE: VSCode (latest version)
Swift Toolchain: [20231211.3](https://github.com/thebrowsercompany/swift-build/releases/tag/20231211.3)
swift-winrt: local nupkg compiled from b261b115d5a5a43950d73046589cc8573fc9ee57

**Steps to reproduce**
- Add `"-include Microsoft.UI.Xaml.Controls.WebView2"` to `SWIFT_WINRT_PARAMETERS` of a `swiftwinrt.cmake` file in a project similar to the `windows-samples` repo.
- Clean the project and run the `swift-winrt` configuration step. Note that the bindings are generated.
- Attempt to build the parent project.

**Expected behavior**
The project should compile.

**Observed behavior**
Compilation fails with the following output:
```
[build] [264/348] Emitting module UWP
[build] C:\Users\biscuit\Documents\Developer\windows-swift-demo\Shared\WinRT\Sources\UWP\UWP+Generics.swift:34381:33: error: 'GUID' is ambiguous for type lookup in this context
[build]     typealias SwiftProjection = GUID
[build]                                 ^~~~
[build] C:\Users\biscuit\Documents\Developer\windows-swift-demo\Shared\WinRT\Sources\WindowsFoundation\Support\cppinteropworkaround.swift:4:18: note: found this candidate
[build] public typealias GUID = CWinRT.GUID_Workaround
[build]                  ^
[build] WinSDK.GUID:1:18: note: found this candidate
[build] public typealias GUID = _GUID
[build]                  ^
[build] C:\Users\biscuit\Documents\Developer\windows-swift-demo\Shared\WinRT\Sources\UWP\UWP+Generics.swift:34379:15: error: type '__x_ABI_C__FIReference_1_GUIDBridge' does not conform to protocol 'AbiBridge'
[build] internal enum __x_ABI_C__FIReference_1_GUIDBridge: ReferenceBridge {
[build]               ^
[build] C:\Users\biscuit\Documents\Developer\windows-swift-demo\Shared\WinRT\Sources\WindowsFoundation\Support\winrtwrapperbase.swift:23:20: note: protocol requires nested type 'SwiftProjection'; add nested type 'SwiftProjection' for conformance
[build]     associatedtype SwiftProjection
[build]                    ^
[build] C:\Users\biscuit\Documents\Developer\windows-swift-demo\Shared\WinRT\Sources\UWP\UWP+Generics.swift:34398:52: error: generic parameter 'Prototype' could not be inferred
[build]     AddRef: { __x_ABI_C__FIReference_1_GUIDWrapper.addRef($0) },
[build]                                                    ^
[build] C:\Users\biscuit\Documents\Developer\windows-swift-demo\Shared\WinRT\Sources\UWP\UWP+Generics.swift:34399:53: error: generic parameter 'Prototype' could not be inferred
[build]     Release: { __x_ABI_C__FIReference_1_GUIDWrapper.release($0) },
[build]                                                     ^
```

**Comment by tristanlabelle** [comment]
This is related to a workaround that we have for C++ interop issues in Swift where we can't directly reference the `GUID` type from `WinSDK` when C++ interop is enabled, so we swap it out with an equivalent definition (`GUID_Workaround`). If you want to look into this, the right-hand side of `typealias SwiftProjection = %` in `write_ireference_init_extension` should probably be generated qualified by a module name so that it resolves to the right `GUID`. I'm surprised that `WinSDK` gets imported in that generated file though. I have a local example with the generated definition below and the file doesn't import WinSDK:

```
internal enum __x_ABI_C__FIReference_1_GUIDBridge: ReferenceBridge {
    typealias CABI = __x_ABI_C__FIReference_1_GUID
    typealias SwiftProjection = GUID

**Comment by biscuitehh** [comment]
Hey @tristanlabelle, sorry for the delay! I haven't had a chance to test things out but I will take a stab at this and report back.

**Comment by stevenbrix** [comment]
yeah the bindings aren't supposed to include `WinSDK`, but they must somehow be implicitly included here? strange

**Comment by stevenbrix** [comment]
really these should just use `Foundation.UUID` IMO
