### ISSUE TITLE
Add @Sendable conformance to generated types.

### ISSUE THREAD

**Issue by jeffdav** [thebrowsercompany/swift-winrt#162]
> Probably tricky for class hierarchies, but maybe straightforward for plain-old-data types like UWP.Color?

**Comment by tristanlabelle** [comment]
We can do this unconditionally for enums, and probably for structs too. Technically a struct could contain an IReference of a delegate type, which would project to an Optional closure type, which wouldn't be sendable, but I don't think it happens in practice.
