### ISSUE TITLE
How to build Swift Windows app using swift-winui but with the latest Windows App SDK 1.5.4 ?

### ISSUE THREAD

**Issue by litewrap** [thebrowsercompany/swift-winrt#175]
The actually available swift-winui package seems tied to the Windows App SDK 1.5/1.5.240205001-preview1.
My experiments apps builds with swift-winui works well except for the busy cursor always showed for few seconds on app launch.
Some search and it seems this know issue in WinUI3 was fixed in most recent version.

So, I would like to build Swift Windows app using swift-winui but using the latest Windows App SDK 1.5.4 (1.5.240607001) and see if the busy cursor problem is fixed.

How can I do that ?

Thanks

**Comment by stevenbrix** [comment]
@litewrap these have been updated. I'll file an action item to create proper releases rather than relying on the main branch

**Comment by tristanlabelle** [comment]
We haven't run into such wait cursor issues at The Browser Company. The Swift projection is unlikely to introduce such an issue, but you could verify by creating an equivalent app in C#. Otherwise, this is likely a problem in WinUI / Windows App SDK or your app's use of it, for which you could get support on Microsoft's repos:
https://github.com/microsoft/WindowsAppSDK or https://github.com/microsoft/microsoft-ui-xaml

**Comment by stevenbrix** [comment]
>Are you reproducing this on your side with the WinUI3AnimationsPreview app?

@litewrap i'll take a look. I hadn't noticed this before

**Comment by stevenbrix** [comment]
@litewrap i do see this, and it does repro in C# if i change the project to run unpackaged, so this seems to be a bug with WinUI or windows app sdk when running unpackaged. Arc is installed as an MSIX, so that's why you don't see this issue

**Comment by litewrap** [comment]
Thanks a lot Steve for taking the time trying to reproduce. On my side I also reproduce the same with the sample C# and C++ WinUI default project with MS Visual Studio, on various PC real and VM. I now understand why Arc installed as MSIX doesn't show this. So nothing related with Swift on Windows or the projections, good to know. Thanks again !
