### ISSUE TITLE
Why do swift-winrt and co force dynamic linking?

### ISSUE THREAD

**Issue by stackotter** [thebrowsercompany/swift-winrt#182]
My project SwiftCrossUI uses WinUI to implement its windows backend, and when I build a simple hello world app with SwiftCrossUI on Windows, the set of required files to distribute the executable adds up to 400mb (not including the Swift runtime). For example, the relies on `WinUI.dll` produced by `swift-winui` which is 114mb. As a quick test I forked `swift-winui` and removed `type: .dynamic` from the `WinUI` product, and my build shrunk by about 114mb since static linking allows unused stuff from `swift-winui` to be omitted.

Is the reason behind forcing dynamic linking legal (license related) or technical?

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by stackotter** [comment]
Apologies if this is a false positive, but that definitely seems fishy (haven't clicked). They replied within seconds and don't seem linked to swift or swift-winrt or thebrowsercompany at all. And the message doesn't make sense for this issue 😅

**Comment by tristanlabelle** [comment]
SPM's build model has an issue where every public symbol gets exported, and Windows has a limit of 65k exported symbols. We built those libraries as dlls to avoid contributing tens of thousands of exported symbols to the consuming executable. I think this was the main reason.

**Comment by stackotter** [comment]
Ah ok, yeah that's what we just found while trying to use static linking. We managed to use static linking for `swift-winui`, but then when we tried to do it for `UWP` as well we hit that limit. Our executable also just grew by the size of WinUI.dll when we statically linked it (I was wrong in my original post), so the compiler clearly didn't do any sort of dead code trimming, making it pointless to statically link anyway (I assume the lack of dead code trimming is related to the public symbol exporting issue).

For now we're gonna try to make some smaller bindings tailored to our use case, sounds like the code size issues with `swift-winui` are more of a Swift on Windows issue than a swift-winui issue. Thanks for the help!

**Comment by tristanlabelle** [comment]
> so the compiler clearly didn't do any sort of dead code trimming, making it pointless to statically link anyway (I assume the lack of dead code trimming is related to the public symbol exporting issue).
> sounds like the code size issues with swift-winui are more of a Swift on Windows issue than a swift-winui issue.

Yes and no. This is a problem when building on Windows **with SPM** because of the way SPM only compiles to object files rather than creating actual static libraries. We've switched to CMake at The Browser Company because of this issue, though we still would like to work with Apple towards fixing this in SPM.
