### ISSUE TITLE
Error when running the powershell script

### ISSUE THREAD

**Issue by DeltriDev** [thebrowsercompany/swift-winrt#183]
I'm writing an issue here because swift-winui does not have an issues page. I am currently trying to shrink the exported dlls that swift-winui and co generate for a swift library that handles multiplatform ui. Many of the features bundled with winui are not used by the project, and they end up creating 300mb of dlls that probably a lot less than that is needed. I forked the winui repo and studied it, and realised that if i edit projection.json to remove stuff our package doesn't use it will probably lower the size of the exported dlls. I tried running the powershell script `generate-bindings.ps1` to check that it works and got this error `Error parsing packages.config file at C:\Users\Alexandros\Code\Fix-CrossUI\swift-winui\.packages\packages.config: '.', hexadecimal value 0x00, is not a valid character. Line 2, position 1.
Nuget restore failed!`

What does this error mean, and how can I fix it? I run it with the swift-winui repo as-is, without editing anything at all

**Comment by stevenbrix** [comment]
hey @DeltriDev can you share the packages.config file that was generated?

**Comment by DeltriDev** [comment]
> hey @DeltriDev can you share the packages.config file that was generated?
I will do it tomorrow morning. But as far as I know it's auto generated by the script, and I did not edit it

**Comment by DeltriDev** [comment]
> hey @DeltriDev can you share the packages.config file that was generated?

here it is! Added a .txt suffix because github doesnt let me share .config files. Just remove the .txt part
[packages.config.txt](https://github.com/user-attachments/files/16919733/packages.config.txt)

**Comment by stevenbrix** [comment]
hmm strange, that file looks correct to me, which shell are you running in?

**Comment by DeltriDev** [comment]
> hmm strange, that file looks correct to me, which shell are you running in?

Powershell, as far as I know. I use the windows terminal but it's powershell

**Comment by stevenbrix** [comment]
ok cool, i'm reproducing this now on a new machine, will update when i have a fix

**Comment by stevenbrix** [comment]
the files are being saved with the wrong encoding, will put up a fix to the generate-bindings script soon

**Comment by DeltriDev** [comment]
> the files are being saved with the wrong encoding, will put up a fix to the generate-bindings script soon

Thank you! Let me know when you push the update :)

**Comment by stevenbrix** [comment]
hey @DeltriDev this should be fixed now! let me know if you're still having any issues

**Comment by ktraunmueller** [comment]
For the record: I ran into the same issue in the swift-windowsfoundation repo. 

The error is fixed by adding `-Encoding ASCII` to the `OutFile` calls in the `generate-bindings.ps1` script. See [my comment here](https://github.com/thebrowsercompany/swift-winrt/issues/189#issuecomment-2554501062).

**Comment by DeltriDev** [comment]
Just realized I never saw that it was fixed... Woops 😅
I no longer use a windows computer, so I won't be able to test it
