### ISSUE TITLE
Missing -Encoding ascii in the swift-windowsfoundation ps1 file

### ISSUE THREAD

**Issue by rayman-zhao** [thebrowsercompany/swift-winrt#189]
Hi, I found the generate-bindings.ps1 will output UTF-8(BOM) files, and failed in later building.

**Comment by tristanlabelle** [comment]
Hi @rayman-zhao , I believe `generate-bindings.ps1` is from one of our other pregenerated repos which have become stale and I have archived. Let us know if we can help using this project directly.

**Comment by ktraunmueller** [comment]
Just for the record: I ran into the same issue when trying to generate the bindings in the swift-windowsfoundation repo:
```
swift-windowsfoundation> .\generate-bindings.ps1
``` 
would fail. 

After adding `-Encoding ASCII` to the two `OutFile` calls it works fine:

![EncodingAscii](https://github.com/user-attachments/assets/7d48787a-d077-4c98-8b51-74df06c77671)
